// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyFirstProject.Data;

#nullable disable

namespace MyFirstProject.Migrations
{
    [DbContext(typeof(HrDbContext))]
    [Migration("20251009165446_addUid")]
    partial class addUid
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MyFirstProject.Models.Attendance", b =>
                {
                    b.Property<int>("AttendanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttendanceId"));

                    b.Property<TimeSpan?>("CheckInTime")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("CheckOutTime")
                        .HasColumnType("time");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EmployeesId")
                        .HasColumnType("int");

                    b.Property<string>("Uid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AttendanceId");

                    b.HasIndex("EmployeesId");

                    b.ToTable("Attendances");
                });

            modelBuilder.Entity("MyFirstProject.Models.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("cities");
                });

            modelBuilder.Entity("MyFirstProject.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EmployeesId")
                        .HasColumnType("int");

                    b.Property<string>("Uid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeesId");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("MyFirstProject.Models.EmployeeStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("employeeStatuses");
                });

            modelBuilder.Entity("MyFirstProject.Models.Employees", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EmployeeStatusId")
                        .HasColumnType("int");

                    b.Property<int?>("JobsId")
                        .HasColumnType("int");

                    b.Property<DateTime>("JoiningDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NationalID")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PhoneNumber")
                        .HasColumnType("int");

                    b.Property<string>("Uid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("EmployeeStatusId");

                    b.HasIndex("JobsId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("MyFirstProject.Models.Jobs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("JobName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Uid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("MyFirstProject.Models.LeaveRequests", b =>
                {
                    b.Property<int>("LeaveID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LeaveID"));

                    b.Property<int?>("EmployeesId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("LeaveDays")
                        .HasColumnType("int");

                    b.Property<int?>("LeaveTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Uid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LeaveID");

                    b.HasIndex("EmployeesId");

                    b.HasIndex("LeaveTypeId");

                    b.ToTable("LeaveRequestss");
                });

            modelBuilder.Entity("MyFirstProject.Models.LeaveType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Leavetype")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("leaveTypes");
                });

            modelBuilder.Entity("MyFirstProject.Models.Attendance", b =>
                {
                    b.HasOne("MyFirstProject.Models.Employees", "employees")
                        .WithMany()
                        .HasForeignKey("EmployeesId");

                    b.Navigation("employees");
                });

            modelBuilder.Entity("MyFirstProject.Models.Department", b =>
                {
                    b.HasOne("MyFirstProject.Models.Employees", "employees")
                        .WithMany()
                        .HasForeignKey("EmployeesId");

                    b.Navigation("employees");
                });

            modelBuilder.Entity("MyFirstProject.Models.Employees", b =>
                {
                    b.HasOne("MyFirstProject.Models.City", "city")
                        .WithMany("employees")
                        .HasForeignKey("CityId");

                    b.HasOne("MyFirstProject.Models.EmployeeStatus", "EmployeeStatus")
                        .WithMany("employees")
                        .HasForeignKey("EmployeeStatusId");

                    b.HasOne("MyFirstProject.Models.Jobs", "jobs")
                        .WithMany("employees")
                        .HasForeignKey("JobsId");

                    b.Navigation("EmployeeStatus");

                    b.Navigation("city");

                    b.Navigation("jobs");
                });

            modelBuilder.Entity("MyFirstProject.Models.Jobs", b =>
                {
                    b.HasOne("MyFirstProject.Models.Department", "department")
                        .WithMany()
                        .HasForeignKey("DepartmentId");

                    b.Navigation("department");
                });

            modelBuilder.Entity("MyFirstProject.Models.LeaveRequests", b =>
                {
                    b.HasOne("MyFirstProject.Models.Employees", "employees")
                        .WithMany()
                        .HasForeignKey("EmployeesId");

                    b.HasOne("MyFirstProject.Models.LeaveType", "leaveType")
                        .WithMany("leaveRequests")
                        .HasForeignKey("LeaveTypeId");

                    b.Navigation("employees");

                    b.Navigation("leaveType");
                });

            modelBuilder.Entity("MyFirstProject.Models.City", b =>
                {
                    b.Navigation("employees");
                });

            modelBuilder.Entity("MyFirstProject.Models.EmployeeStatus", b =>
                {
                    b.Navigation("employees");
                });

            modelBuilder.Entity("MyFirstProject.Models.Jobs", b =>
                {
                    b.Navigation("employees");
                });

            modelBuilder.Entity("MyFirstProject.Models.LeaveType", b =>
                {
                    b.Navigation("leaveRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
